# ----------------------------------------------------------------------------------------------------------------------
# Artemis-Prod-Postgres Setup
# ----------------------------------------------------------------------------------------------------------------------

services:
    artemis-app:
        extends:
            file: ./artemis.yml
            service: artemis-app
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        volumes:
            - /srv/artemis/docker/.docker-data/artemis-data:/opt/artemis/data
        environment:
            ARTEMIS_USERMANAGEMENT_INTERNALADMIN_PASSWORD: $ARTEMIS_USERMANAGEMENT_INTERNALADMIN_PASSWORD
        env_file:
            - ./artemis/config/postgres.env
    postgres:
        extends:
            file: ./postgres.yml
            service: postgres
        restart: unless-stopped
        volumes:
            - /srv/artemis/docker/.docker-data/artemis-postgres-data:/var/lib/postgresql/data
    nginx:
        extends:
            file: ./nginx.yml
            service: nginx
        # the artemis-app service needs to be started, otherwise there are problems with name resolution in docker
        depends_on:
            artemis-app:
                condition: service_started
        restart: unless-stopped

networks:
    artemis:
        driver: "bridge"
        name: artemis
