# ----------------------------------------------------------------------------------------------------------------------
# Nginx base service
# ----------------------------------------------------------------------------------------------------------------------

services:
    nginx:
        # nginx setup based on artemis prod ansible repository
        container_name: artemis-nginx
        image: docker.io/library/nginx:1.28.0-alpine-slim
        pull_policy: missing
        volumes:
          - /srv/artemis/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - /srv/artemis/docker/nginx/timeouts.conf:/etc/nginx/conf.d/timeouts.conf:ro
          - /srv/artemis/docker/nginx/artemis-nginx.conf:/etc/nginx/conf.d/artemis-nginx.conf:ro
          - /srv/artemis/docker/nginx/artemis-upstream-single-node.conf:/etc/nginx/includes/artemis-upstream.conf:ro
          - /srv/artemis/docker/nginx/artemis-ssh-upstream-single-node.conf:/etc/nginx/includes/artemis-ssh-upstream.conf:ro
          - /srv/artemis/docker/nginx/artemis-server.conf:/etc/nginx/includes/artemis-server.conf:ro
          - /srv/artemis/docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
          - /srv/artemis/docker/nginx/nginx_503.html:/usr/share/nginx/html/503.html:ro
          - /srv/artemis/docker/nginx/70-artemis-setup.sh:/docker-entrypoint.d/70-artemis-setup.sh
          - /srv/cert/server.crt:/certs/server.pem:ro
          - /srv/cert/server.key:/certs/server.key:ro
        # ulimits adopted from the nginx_security_limits.conf in the Artemis ansible collection
        ulimits:
            nofile:
                soft: 50000
                hard: 1048576
        ports:
            - "80:80"
            - "443:443/tcp"
            - "443:443/udp" # HTTP/3
            - "7921:7921" # Git SSH
        # expose the port to make it reachable docker internally even if the external port mapping changes
        expose:
            - "80"
            - "443"
            - "7921" # Git SSH
        healthcheck:
            test: service nginx status || exit 1
            start_period: 60s
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis
